#ifndef LINUXSERVER_SOCKET_SERVERFILESOCKET_H
#define LINUXSERVER_SOCKET_SERVERFILESOCKET_H

#define SERVER_FILE_PORT 36976

#define MAX_LISTEN 64 * 1024

//文件传输的socket
void *createServerFileSocket(void *arg);

#endif //LINUXSERVER_SOCKET_SERVERFILESOCKET_H
